import Foundation

enum PortNameCatalog {
    static let all: [String] = [
        "Port of Rotterdam",
        "Port of Antwerp-Bruges",
        "Port of Hamburg",
        "Port of Amsterdam",
        "Port of Le Havre",
        "Port of Marseille Fos",
        "Port of Genoa",
        "Port of Valencia",
        "Port of Barcelona",
        "Port of Algeciras",
        "Port of Lisbon",
        "Port of Sines",
        "Port of Piraeus",
        "Port of Thessaloniki",
        "Port of Istanbul",
        "Port of Izmir",
        "Port of Mersin",
        "Port of Alexandria",
        "Port Said",
        "Port of Casablanca",
        "Port of Tangier Med",
        "Port of Durban",
        "Port of Cape Town",
        "Port of Mombasa",
        "Port of Djibouti",
        "Port of Lagos",
        "Port of Tema",
        "Port of Abidjan",
        "Port of Dakar",
        "Port of Walvis Bay",
        "Port of Singapore",
        "Port Klang",
        "Port of Tanjung Pelepas",
        "Port of Jakarta",
        "Port of Surabaya",
        "Port of Bangkok",
        "Port of Laem Chabang",
        "Port of Ho Chi Minh City",
        "Port of Hai Phong",
        "Port of Manila",
        "Port of Cebu",
        "Port of Kaohsiung",
        "Port of Keelung",
        "Port of Hong Kong",
        "Port of Shenzhen",
        "Port of Guangzhou",
        "Port of Xiamen",
        "Port of Ningbo-Zhoushan",
        "Port of Shanghai",
        "Port of Qingdao",
        "Port of Tianjin",
        "Port of Dalian",
        "Port of Busan",
        "Port of Incheon",
        "Port of Tokyo",
        "Port of Yokohama",
        "Port of Nagoya",
        "Port of Kobe",
        "Port of Osaka",
        "Port of Hakata",
        "Port of Vladivostok",
        "Port of Mumbai",
        "Port of Nhava Sheva",
        "Port of Chennai",
        "Port of Kolkata",
        "Port of Kochi",
        "Port of Visakhapatnam",
        "Port of Colombo",
        "Port of Chittagong",
        "Port of Karachi",
        "Port of Jebel Ali",
        "Port of Abu Dhabi",
        "Port of Doha",
        "Port of Dammam",
        "Port of Jeddah",
        "Port of Salalah",
        "Port of Muscat",
        "Port of Aqaba",
        "Port of Haifa",
        "Port of Ashdod",
        "Port of Sydney",
        "Port of Melbourne",
        "Port of Brisbane",
        "Port of Fremantle",
        "Port of Adelaide",
        "Port of Auckland",
        "Port of Wellington",
        "Port of Tauranga",
        "Port of Suva",
        "Port of Noumea",
        "Port of Vancouver",
        "Port of Prince Rupert",
        "Port of Montreal",
        "Port of Halifax",
        "Port of Saint John",
        "Port of Quebec",
        "Port of New York and New Jersey",
        "Port of Boston",
        "Port of Philadelphia",
        "Port of Baltimore",
        "Port of Norfolk",
        "Port of Charleston",
        "Port of Savannah",
        "Port of Miami",
        "Port Everglades",
        "Port of Jacksonville",
        "Port of Tampa Bay",
        "Port of New Orleans",
        "Port of Houston",
        "Port of Corpus Christi",
        "Port of Los Angeles",
        "Port of Long Beach",
        "Port of Oakland",
        "Port of Seattle",
        "Port of Tacoma",
        "Port of San Diego",
        "Port of Manzanillo",
        "Port of Lazaro Cardenas",
        "Port of Veracruz",
        "Port of Altamira",
        "Port of Colon",
        "Port of Balboa",
        "Port of Cartagena",
        "Port of Barranquilla",
        "Port of Guayaquil",
        "Port of Callao",
        "Port of Valparaiso",
        "Port of San Antonio",
        "Port of Buenos Aires",
        "Port of Montevideo",
        "Port of Santos",
        "Port of Rio de Janeiro",
        "Port of Paranagua",
        "Port of Itajai",
        "Port of Salvador",
        "Port of Recife",
        "Port of Belem"
    ]

    static func randomName() -> String {
        all.randomElement() ?? "Port of Rotterdam"
    }

    static func randomDisplayName() -> String {
        normalizedDisplayName(for: randomName())
    }

    static func normalizedDisplayName(for name: String) -> String {
        if name.hasPrefix("Port of ") {
            return String(name.dropFirst("Port of ".count))
        }
        return name
    }
}
